### ISSUE TITLE
loadSuccessor is not doing anything and blocking the code

### ISSUE THREAD

**Issue by qqpann** [rahul13ramesh/SuccessorOptions#1]
Thanks for your paper and code.

I tried to run each python script and found that buildPoliciesSuccessor not working.
I figured out that `saveSuccessor` is not used anywhere and you are not saving the CSV file in this repository.
And `loadSuccessor` is actually just loading all zero NumPy arrays, which is already initiated inside `__init__`.
Does just deleting `loadSuccessor` work?

**Comment by rahul13ramesh** [comment]
Hey, I am unable to reproduce the error.  No,  `loadSuccessor` cannot be removed and loads the successor representations of each state.  `sucessor1.csv` is not an all zero Numpy array

`buildPoliciesSuccessor` is used to create the files in `data/dat*/policies` (which are also provided in the repo).
